PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX n2o: <http://n2o.neo/property/>
PREFIX n2oc: <http://n2o.neo/custom/>
PREFIX dct: <http://purl.org/dc/terms/>

CONSTRUCT {
  ?dataset ?dsrel ?dsval . 
	?image ?imgrel ?imgval .
	?channel ?channelrel ?channelval .
}

	WHERE {
	
	?dataset n2o:nodeLabel ?nodelabel . # This selects all datasets
	
	OPTIONAL {
  	?dataset n2oc:production ?production .
		# n2oc:production is a bit brittle because IRI might be changed (risk!)
	}
	
	?dataset ?dsrel ?dsval .
  
  OPTIONAL {
  	 ?image dct:source ?dataset . #in case a dataset does not have images yet this is an optional clause
		 ?image ?imgrel ?imgval .
	}
  
  OPTIONAL {
  	?channel <http://xmlns.com/foaf/0.1/depicts> ?image . # There does not always seem to be a channel
		?channel ?channelrel ?channelval .
  }
	
  FILTER(?production=false || !bound(?production)) .
  FILTER(?nodelabel="DataSet") 
}