PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX n2o: <http://n2o.neo/property/>
PREFIX n2oc: <http://n2o.neo/custom/>
PREFIX dct: <http://purl.org/dc/terms/>

# MATCH (ds:DataSet) where ds.production
# WITH ds
# MATCH lp=(ds)-[:has_license]-(l:License)
# WITH ds, lp
# OPTIONAL MATCH pp=(ds)-[:has_reference]->(p:pub)
# WITH ds, lp, pp
# MATCH ip=(ds)<-[:has_source]-(i:Individual)<-[:depicts]-(ch:Individual)-[:in_register_with]->(tc:Individual)-[:depicts]-(t)
# WITH ds, lp, pp, ip, i
# MATCH icp=(i)-[:INSTANCEOF|Related|hasDbXref]->(c)
# RETURN lp,pp, ip, icp limit 2

SELECT ?image ?channel ?dataset ?license ?reference WHERE {
  ?dataset n2o:nodeLabel ?nodelabel ; # This selects all datasets
  n2oc:production ?production .
    # n2o:production is a bit brittle because IRI might be changed (risk!)
  
  OPTIONAL {
    ?dataset <http://purl.org/dc/terms/license> ?license . # Do we need to delete this?
  }
  
  OPTIONAL {
    ?dataset dct:references ?reference . # Do we need to delete these?
  }
	OPTIONAL {
  	 ?image dct:source ?dataset . #in case a dataset does not have images yet this is an optional clause
	}
  
  OPTIONAL {
  	?channel <http://xmlns.com/foaf/0.1/depicts> ?image . # There does not always seem to be a channel
  }
	
  FILTER(?production=false) .
  FILTER(?nodelabel="DataSet") 
}